import {test} from 'node:test';
import assert from 'node:assert/strict';
import {rewardOutcomes,rewardType} from '../src/domain/reward-history';
import type {ParentReward} from '../src/domain/types';
const reward=(id:string,type:ParentReward['type'],receipt_id:string|null,redeemed=true)=>({id,type,receipt_id,code:'123456',reason:'',created_at:'2026-09-01',expires_at:'2026-10-01',redeemed_at:redeemed?'2026-09-02':null,revoked_at:null});
test('reward entry accepts only supported single values',()=>{assert.equal(rewardType('evolution'),'evolution');assert.equal(rewardType('legendary'),'legendary');for(const value of [undefined,'bad',['evolution']])assert.equal(rewardType(value),'capture');});
test('capture result follows its receipt, not reward order',()=>{const result=rewardOutcomes([reward('a','capture','r2'),reward('b','capture','r1')],[],[{id:'r1',pokemon_id:25,from_pokemon_id:null},{id:'r2',pokemon_id:4,from_pokemon_id:null}]);assert.equal(result[0].outcome?.pokemonId,4);assert.equal(result[1].outcome?.pokemonId,25);});
test('tickets distinguish stored from used and use the use receipt rather than claim receipt',()=>{const result=rewardOutcomes([reward('a','evolution','claim'),reward('b','evolution','claim2'),reward('c','legendary','claim3')],[{reward_id:'b',used_at:null,receipt_id:null},{reward_id:'a',used_at:'2026-09-03',receipt_id:'evolved'},{reward_id:'c',used_at:'2026-09-04',receipt_id:'legend'}],[{id:'claim',pokemon_id:null,from_pokemon_id:null},{id:'evolved',pokemon_id:5,from_pokemon_id:4},{id:'legend',pokemon_id:144,from_pokemon_id:null}]);assert.deepEqual(result[0].outcome,{state:'used',usedAt:'2026-09-03',pokemonId:5,fromPokemonId:4});assert.equal(result[1].outcome?.state,'stored');assert.equal(result[2].outcome?.pokemonId,144);});
test('unredeemed rewards have no result; missing old records do not invent a partner or unused ticket',()=>{const result=rewardOutcomes([reward('a','capture',null,false),reward('b','evolution',null)],[],[]);assert.equal(result[0].outcome,undefined);assert.equal(result[1].outcome?.state,'received');assert.equal(result[1].outcome?.pokemonId,null);});
