'use client';
import {useEffect,useState} from 'react';
import {BookOpen,Check,ChevronDown,Clock3,Coins,History,SlidersHorizontal,Star,Sparkles} from 'lucide-react';
import {api} from '@/lib/api-client';
import {stages,type LearningState} from '@/domain/learning';
import {usageDay} from '@/domain/play-time';
export function ParentLearning(){
 const [data,setData]=useState<LearningState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[stage,setStage]=useState(0),[fixed,setFixed]=useState(false),[rounds,setRounds]=useState(2),[notice,setNotice]=useState('');
 async function load(){try{const d=await api<LearningState>('parent/learning');setData(d);setStage(d.fixedStage??d.stage);setFixed(d.fixedStage!==null);setRounds(d.dailyRounds);setError('');}catch(e){setError(e instanceof Error?e.message:'读取失败。');}}
 useEffect(()=>{let mounted=true;api<LearningState>('parent/learning').then(d=>{if(mounted){setData(d);setStage(d.fixedStage??d.stage);setFixed(d.fixedStage!==null);setRounds(d.dailyRounds);}}).catch(e=>{if(mounted)setError(e.message);});return()=>{mounted=false;};},[]);
 async function save(){setBusy(true);setError('');try{const d=await api<LearningState>('parent/learning',{action:'settings',stage,fixed,dailyRounds:rounds,requestId:crypto.randomUUID()});setData(d);setNotice('已保存，下一轮生效');}catch(e){setError(e instanceof Error?e.message:'保存失败。');}finally{setBusy(false);}}
 const [today]=useState(()=>usageDay(Date.now()));const lessons=data?[...data.history.filter(l=>l.finishedAt),...(data.active&&!data.active.finishedAt?[data.active]:[])].filter(l=>l.day===today):[];
 const questions=lessons.flatMap(l=>l.questions).filter(q=>q.done);
 const dirty=!!data&&(stage!==(data.fixedStage??data.stage)||fixed!==(data.fixedStage!==null)||rounds!==data.dailyRounds);
 return <section className="detail-panel parent-learning"><div className="section-heading"><h2><BookOpen size={22}/>学习手帐</h2><span className="learning-day">今日 · {today.slice(5).replace('-',' / ')}</span></div>{error&&<p role="alert" className="form-error">{error}<button className="text-link" onClick={()=>void load()}>重新读取</button></p>}{data?<>
 <div className="learning-stats">{[{label:'今日完成',value:questions.length,unit:'题',Icon:BookOpen},{label:'独立答对',value:questions.filter(q=>q.first).length,unit:'题',Icon:Check},{label:'提示后完成',value:questions.filter(q=>q.hint).length,unit:'题',Icon:Sparkles},{label:'练习时间',value:Math.ceil(lessons.reduce((n,l)=>n+l.activeSeconds,0)/60),unit:'分钟',Icon:Clock3},{label:'可用学习星',value:data.balance,unit:'颗',Icon:Star},{label:'已兑换招式',value:data.unlocked.length,unit:'招',Icon:Coins}].map(({label,value,unit,Icon})=><div className="learning-stat" key={label}><span><Icon size={17}/>{label}</span><strong>{value}<small>{unit}</small></strong></div>)}</div>
 <div className="learning-config"><h3><SlidersHorizontal size={18}/>练习安排</h3><div className="learning-config-grid"><label className="learning-field">减法阶段<select disabled={busy} value={stage} onChange={e=>{setStage(Number(e.target.value));setNotice('');}}>{stages.map((s,i)=><option key={s.name} value={i}>{s.name}</option>)}</select></label><label className="learning-field">每日奖励轮数<select disabled={busy} value={rounds} onChange={e=>{setRounds(Number(e.target.value));setNotice('');}}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'不奖励学习星':`${n} 轮 · 最多 ${n*10} 星`}</option>)}</select></label><label className="learning-fixed"><input type="checkbox" disabled={busy} checked={fixed} onChange={e=>{setFixed(e.target.checked);setNotice('');}}/><span><strong>固定当前阶段</strong><small>{fixed?'按当前阶段持续练习':'根据完成情况逐步进阶'}</small></span></label></div><div className="learning-config-footer"><p>每轮 5 题，每日轮次按北京时间重置。</p><button className="button" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'正在保存…':dirty?'保存设置':'已保存'}</button></div>{notice&&<p role="status" className="form-note">{notice}</p>}</div>
 <div className="learning-records"><details><summary><History size={19}/><strong>练习记录</strong><span>{data.history.length} 轮</span><ChevronDown size={18}/></summary><div className="learning-record-body">{[...data.history].reverse().slice(0,20).map(l=><div className="learning-record" key={l.id}><div><strong>{stages[l.stage].name}</strong><small>{l.day}</small></div><span>独立 {l.questions.filter(q=>q.first).length}/5 · 提示 {l.questions.filter(q=>q.hint).length} 次</span></div>)}{data.history.length===0&&<p className="learning-record-empty">完成第一轮练习后，会在这里留下记录。</p>}</div></details><details><summary><Star size={19}/><strong>学习星收支</strong><span>余额 {data.balance}</span><ChevronDown size={18}/></summary><div className="learning-record-body">{[...data.ledger].reverse().slice(0,30).map((r,i)=><div className="learning-record" key={`${r.id}-${i}`}><div><strong>{r.reason}</strong><small>{new Date(r.at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</small></div><b className={r.amount>0?'star-income':'star-expense'}>{r.amount>0?'+':''}{r.amount}<Star size={14}/></b></div>)}{data.ledger.length===0&&<p className="learning-record-empty">获得或兑换学习星后，可以在这里查看收支。</p>}</div></details></div></>:<p role="status">正在读取…</p>}</section>;
}
