import { readFileSync, writeFileSync } from 'node:fs';
import data from '../src/data/battle-learnsets.json';
const file='supabase/migrations/202609240005_battle_loadouts.sql';
const rules=Object.fromEntries(Object.entries(data.pokemon).map(([id,pools])=>[id,{level:pools.level.map(m=>m.id),machine:pools.machine.map(m=>m.id)}]));
const generated=`-- BEGIN GENERATED MOVE RULES\n-- ${data.meta.ruleset}; generated by scripts/generate-move-rules.ts\ncreate function public.kanto_move_rules() returns jsonb language sql immutable set search_path = '' as $rules$\n select '${JSON.stringify(rules)}'::jsonb;\n$rules$;\nrevoke all on function public.kanto_move_rules() from public, anon, authenticated;\n-- END GENERATED MOVE RULES`;
const sql=readFileSync(file,'utf8');
const next=sql.replace(/-- BEGIN GENERATED MOVE RULES[\s\S]*?-- END GENERATED MOVE RULES/,generated);
if(process.argv.includes('--check')){if(next!==sql)throw new Error('Move SQL rules are stale. Run npm run sql:rules.');}
else writeFileSync(file,next);
